name: GitHub Pages Deployment
on:
  push:
    branches:
      - main
env:
  FORCE_COLOR: 1
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"

      - name: Install NPM dependencies
        run: npm ci

      - name: Build website
        run: go run .

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "static"

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4.0.5

    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
