name: Vercel Deployment
on:
  push:
    branches:
      - main
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
jobs:
  Deploy:
    runs-on: ubuntu-latest

    permissions:
      deployments: write

    steps:
      - name: Create GitHub deployment
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: ${{ github.token }}
          environment-url: https://hermannm.dev
          environment: Production
          # False, to let GitHub automatically mark old deployments as inactive
          # See https://docs.github.com/en/rest/deployments/deployments?apiVersion=2022-11-28#inactive-deployments
          production-environment: false

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"

      - name: Install NPM dependencies
        run: npm ci

      - name: Build website
        run: go run .

      - name: Move build to location expected by Vercel
        run: mv static .vercel/output

      - name: Pull Vercel environment information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: "Update GitHub deployment: Success"
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ github.token }}
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: success

      - name: "Update GitHub deployment: Failure"
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ github.token }}
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: failure
