name: Vercel Deployment
on:
  push:
    branches:
      - main
jobs:
  Deploy:
    runs-on: ubuntu-latest

    permissions:
      deployments: write

    steps:
      - name: Create GitHub deployment
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: ${{ github.token }}
          environment-url: https://hermannm.dev
          environment: Production
          # Set to false to automatically mark old deployments as inactive
          # See https://docs.github.com/en/rest/deployments/deployments?apiVersion=2022-11-28#inactive-deployments
          production-environment: false

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.20.0"

      - name: Install formatter
        run: npm install

      - name: Build website
        run: go run .

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          github-comment: false
          vercel-args: "--prod"
          working-directory: static

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ github.token }}
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: success

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ github.token }}
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: failure
