name: Vercel Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.20.0"
      - name: Install NPM dependencies
        run: npm install
      - name: Build website
        run: go run .
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel environment information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Move build to Vercel output directory
        run: mkdir --parents .vercel/output; mv ./static/* .vercel/output/
      - name: Deploy website to Vercel
        # prettier-ignore
        run: vercel deploy --prebuilt --prod --local-config=./vercel.json --token=${{ secrets.VERCEL_TOKEN }}
